bug:
  - '- :bug: Bug'
feature-long-term:
  - '- :heavy_plus_sign: Feature request'
performance:
  - '- :snail: Performance issue'
question:
  - '- :question: Question'

mc-1.12:
  - 'Minecraft: 1.12'
mc-1.14:
  - 'Minecraft: 1.14'
mc-1.15:
  - 'Minecraft: 1.15'
mc-1.16:
  - 'Minecraft: 1.16'
mc-1.18:
  - 'Minecraft: 1.18'
mc-1.19:
  - 'Minecraft: 1.19'
mc-1.20:
  - 'Minecraft: 1.20'
mc-1.21:
  - 'Minecraft: 1.21'
mc-26:
  - 'Minecraft: 26'
mc-27:
  - 'Minecraft: 27'
mc-28:
  - 'Minecraft: 28'
mc-29:
  - 'Minecraft: 29'
mc-30:
  - 'Minecraft: 30'
