# Project
mod_version=1.24.1
group=org.cyclops.integrateddynamics
java_version=25

# Common
minecraft_version=26.1.1
mod_name=IntegratedDynamics
mod_author=rubensworks (aka kroeser)
mod_id=integrateddynamics
license=MIT
github_url=https://github.com/CyclopsMC/IntegratedDynamics
issue_tracker_url=https://github.com/CyclopsMC/IntegratedDynamics/issues
display_url=https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics
description=Take full and automated control of your appliances.
fingerprint=bd0353b3e8a2810d60dd584e256e364bc3bedd44

curseforge_project_id=236307
modrinth_project_id=yYzdQHJI

# NeoForge
neoforge_version=26.1.1.1-beta
neoforge_loader_version_range=[4,)
neoforge_update_json_url=https://raw.githubusercontent.com/CyclopsMC/Versions/master/neoforge_update/integrated-dynamics.json

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true

# Dependencies
cyclopscore_version=1.25.5-974
integrateddynamicscompat_version=1.0.0-122
commoncapabilities_version=2.9.7-335
